### PR TITLE
Updated Ember-CLI to 1.13.12 and ran `ember init`

### PR DESCRIPTION
**Pull request by martndemus**
- [x] Needs some linter fixings.

### CODE REVIEW

**Comment by rwjblue** [comment]
Looks like most of the failures are for `unused: true` in `tests/.jshintrc`.  You could remove that change from here, and fix that separately (definitely should be a separate commit if you decide to fix in this PR).

**Comment by martndemus** [comment]
Needs #54 to be merged in first.

**Comment by rwjblue** [comment]
#54 is in, can you rebase?

**Comment by martndemus** [comment]
Rebased

**Comment by rwjblue** [comment]
Thank you!

**Pull request merged**
