### PR TITLE
Expand properties on computed decorators

### PR DESCRIPTION
**Pull request by martndemus**
Solves #38

### CODE REVIEW

**Comment by rwjblue** [comment]
Can you add the new `ember-1-13-x` and `ember-2-0-x` scenarios to `.travis.yml` (can be a separate PR though).

**Comment by rwjblue** [comment]
This is a breaking change (arguments to callback changes), so I'll release master first then we can bump properly.

**Comment by martndemus** [comment]
@rwjblue d'oh.

**Comment by rwjblue** [comment]
Released as v0.2.0

**Pull request merged**
