### PR TITLE
CoreObject 1.x and 2.x Compat Fix

### PR DESCRIPTION
**Pull request by broerse**

### CODE REVIEW

**Comment by rwjblue** [comment]
We shouldn't need to do this if we are not already overriding init. Did you get a deprecation here?

**Comment by broerse** [comment]
Yes I got a deprecation error from ember-cli 2.6.2

**Comment by rwjblue** [comment]
Can you share the output?

**Comment by broerse** [comment]
```
C:\dev\ember-cli-blog>ember s
DEPRECATION: Overriding init without calling this._super is deprecated. Please call `this._super.init && this._super.init.apply(this, arguments);` addon: `ember-data`
    at Function.Addon.lookup (C:\dev\ember-cli-blog\node_modules\ember-cli\lib\models\addon.js:896:27)
DEPRECATION: Overriding init without calling this._super is deprecated. Please call this._super(), addon: `ember-cli-font-awesome`
    at Function.Addon.lookup (C:\dev\ember-cli-blog\node_modules\ember-cli\lib\models\addon.js:896:27)
DEPRECATION: Overriding init without calling this._super is deprecated. Please call `this._super.init && this._super.init.apply(this, arguments);` addon: `ember-cli-pagination`
    at Function.Addon.lookup (C:\dev\ember-cli-blog\node_modules\ember-cli\lib\models\addon.js:896:27)
DEPRECATION: Addon: `ember-cli-font-awesome` is missing addon.project, this may be the result of an addon forgetting to invoke `super` in its init.
DEPRECATION: Addon: `ember-computed-decorators` is missing addon.project, this may be the result of an addon forgetting to invoke `super` in its init.
DEPRECATION: Addon: `ember-cli-font-awesome` is missing addon.project, this may be the result of an addon forgetting to invoke `super` in its init.
Livereload server on http://localhost:49152
Serving on http://localhost:4200/
```

**Comment by broerse** [comment]
Switching to `ember-font-awesome` also fixes the `ember-computed-decorators` deprecation.

**Comment by rwjblue** [comment]
Ahh, gotcha. Yes, this is an issue with ember-font-awesome (not here).  Since ember-font-awesome is depending on ember-computed-decorators and when ember-computed-decorators is created it does not get properly initialized (since addons are responsible for instantiating their own addon children).

**Pull request closed without merging**
